### ISSUE TITLE
How to use multiple SSL certificates?

### ISSUE THREAD

**Issue by keyur2maru** [murphye/cheap-gke-cluster#28]
How can one add support for multiple SSL certificates and use SNI to route to the correct virtual service? I was able to modify https.tf as follows which ended up reflecting multiple certificates in the regional load balancer but couldn't get the health check to pass anymore.
Here is what I found on Gloo Gateway docs -

> Gloo Gateway allows you to serve multiple virtual hosts from a single HTTPS port and use [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) to determine which certificate to present to which virtual host.

https://docs.solo.io/gloo-edge/main/guides/security/tls/server_tls/#serving-certificates-for-multiple-virtual-hosts-with-sni

```
locals {
  ssl_certificate_ids = [for cert in google_compute_region_ssl_certificate.certs : cert.id]
}

resource "google_compute_region_ssl_certificate" "certs" {
  for_each = var.ssl_certificates

  provider    = google-beta
  project     = google_compute_subnetwork.default.project
  region      = google_compute_subnetwork.default.region
  name        = each.value.name
  description = "SSL certificate for ${each.key}"
  private_key = file(each.value.key_path)
  certificate = file(each.value.cert_path)
}

# https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_ssl_certificate#example-usage---ssl-certificate-target-https-proxies
resource "google_compute_region_target_https_proxy" "default" {
  provider = google-beta
  project  = google_compute_subnetwork.default.project
  region   = google_compute_subnetwork.default.region
  name     = "l7-xlb-proxy-https"
  url_map  = google_compute_region_url_map.default.id
  ssl_certificates = local.ssl_certificate_ids
  
  depends_on = [
    google_compute_region_ssl_certificate.certs
  ]
}
```

**Comment by keyur2maru** [comment]
Found out the root cause of the issue, the health check `l7-xlb-basic-check-http` was set up to hit the "/" endpoint which was failing if the virtual service was restricted to a certain domain. The solution was to add one virtual service with a wildcard entry for domain, solely to keep the health check happy. My virtual service looked something like this -
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /
      directResponseAction:
        status: 200
        body: "Health Check"
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-2
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - 'api.example.com'
    routes:
    - matchers:
      - exact: /api/example
      directResponseAction:
        status: 200
        body: "Hello from API Example"
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-3
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - 'dev.api.example.com'
    routes:
    - matchers:
      - exact: /api/example
      directResponseAction:
        status: 200
        body: "Hello from Dev API Example"
```
